apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-used # the name is not used if a target is specified in kustomization.yaml
  labels: 
    local: false
    region: C
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: region
                operator: In
                values:
                - C
